import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import ModalProvider from "@/components/Modal-Provider";

const inter = Inter({ subsets: ["latin"] });

import dynamic from "next/dynamic";

export const metadata: Metadata = {
  title: "FlashAI",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const CrispWithNoSSR = dynamic(() => import("@/lib/crisp"));
  return (
    <ClerkProvider>
      <html lang="en">
        <CrispWithNoSSR />
        <body className={inter.className}>
          <ModalProvider />
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
